# Dart ffigen config YAML
---
output: ./lib/generated_bindings.dart
name: FFIApi
description: cpp APIs

headers:
  entry-points:
    - ./cpp/ffi_api.h

comments:
  style: any
  length: full

llvm-path:  
  - "/opt/homebrew/opt/llvm"
