// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// cpp APIs
class FFIApi {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FFIApi(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FFIApi.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void makeCrash(
    int type,
  ) {
    return _makeCrash(
      type,
    );
  }

  late final _makeCrashPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>('makeCrash');
  late final _makeCrash = _makeCrashPtr.asFunction<void Function(int)>();
}
